### ISSUE TITLE
Unable to extract the zip file post download

### ISSUE THREAD

**Issue by danaidu431** [PacktWorkshops/The-Applied-SQL-Data-Analytics-Workshop#1]

**Comment by PacktSupport** [comment]
Hello danaidu431, thank you for your patience! We have updated the preface of the workshop in the new version published on 30th July 2020. For now, you can follow the instructions provided [here](https://github.com/PacktWorkshops/The-Applied-SQL-Data-Analytics-Workshop/issues/2#issuecomment-720703323) to load the sample database. Let us know if you are still facing any issues. Thanks!
