### ISSUE TITLE
Can't find sqlda 

### ISSUE THREAD

**Issue by cidones** [PacktWorkshops/The-Applied-SQL-Data-Analytics-Workshop#2]
Hi there,

I've download all files and i'm working on exercise 1.06. However i can't find sqlda to connect to a sql client.

Please advise

**Comment by kleyersoma** [comment]
It is such a shame, forgetting in more 400 pages how to specify the query for the creation of database, I also noticed that the authors of this book are the same of SQL for Data Analytics and its content in most of the chapters is the same and guess what they also "forgot"; to upload the query for the database creation and its data... They are playing, they are not teaching.

**Comment by perhak** [comment]
It's all in the preface of the book.

**Comment by siddatla** [comment]
perhak would you be kind enough to share how you were able to get the sqlda? i see that there is a data.dump file ... which I imagine contains a series of scripts to recreate the sqlda database? 

However, I am unsure as to how I should be opening it?

**Comment by siddatla** [comment]
i have both SSMS and Anaconda installed on my machine. All I need is to get the sqlda database loaded into SSMS and I should be good from there. 

I have reached out to PACKT to contact the author for some help getting the sqlda loaded as I too am finding it confusing or non existent. 

Will share any / all feedback once I get it. 

The material itself seems very useful and well written just need that sweet sweet data :)

Cheers

**Comment by mschiddy** [comment]
Here's how I got sqlda on my Windows 10 PC.  

1. I first installed psql and python as instructed in the preface of the book. 
2.  I had to add the Envionmental Variable to the psql path just as the text instructs. Then I ran the commands to log into the psql schema as instructed and restart my computer to get the Windows OS to recognize the change. 
3.  Then I reopened my Windows command prompt and typed:  psql postgres   to list the existing psql schemas.  sqlda won't yet exist, so you need to create it with:  CREATE DATABASE sqlda;  If that gives an error, try CREATEDB sqlda;
4.  Back to the browser, in GitHub I clicked on the raw file option which opened the data.dump sql query commands and comments in my Chrome browser tab with URL: https://raw.githubusercontent.com/PacktWorkshops/The-Applied-SQL-Data-Analytics-Workshop/master/Datasets/data.dump
4.  Click anywhere within the browser tab and choose:  CTRL + A to select all of the content in the browser window.
5.  Open a simple code compiler like free Notepad++  and create a new file, paste the browser contents into Notepad++ with CTRL + V.  Save as data.dump in your downloads folder or wherever you want to navigate in your psql command where you execute it.
6.  Follow the instructions in the book for running the psql command from the Windows command prompt to download the data.dump file.  For example, if your file is located in C:\Users\Me\Downloads and you named it data.dump, you'd run psql -U postgres -d sqlda -f C:\Users\Me\Downloads\data.dump  
7.  If it succeeds, the output should match the textbook.  If it fails, you probably have a typo in your filepath or provided the wrong one.

The files will be downloaded into the sqlda database.

**Comment by PacktSupport** [comment]
Great discussion everyone! Thanks mschiddy for sharing the detailed steps to download and load the database. A new version of the workshop was published on 30th July 2020 where we have shared the detailed steps to load the database. Let us know if you are still facing any issues. Thanks!
